name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore & Publish
        run: |
          dotnet restore
          dotnet publish -c Release -o publish

      - name: Sync build to Droplet
        uses: burnett01/rsync-deployments@v4
        with:
          switches: -avz --delete --exclude '*.db'
          path: publish/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: /home/${{ secrets.SSH_USER }}/buu_duyuru_bot

      - name: Restart service on Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl restart buu_duyuru_bot.service
