name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore & Publish
        run: |
          dotnet restore
          dotnet publish --configuration Release --output ./publish

      - name: Deploy to Droplet via rsync
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-avz --delete --exclude='*.db'"
          SOURCE: "publish/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "/home/${{ secrets.SSH_USER }}/buu_duyuru_bot"
          EXCLUDE: ".git*"

      - name: Restart service on Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Attempting to restart service..."
            sudo systemctl restart buu_duyuru_bot.service
            echo "Service restart command executed."
